# Generated by Django 4.0.4 on 2022-07-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='views',
            name='test',
            field=models.TextField(),
        ),
    ]
